spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cineflix
    username: root
    password: Admin2023!
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/master.xml
    contexts: prod
  h2:
    console:
      enabled: false

