spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: db/changelog/master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
